In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
##sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]#These are my set of questions which i am going to specially use

In [21]:
#Define the vocabulary size
voc_size=10000

In [22]:
##One Hot Representation for every word
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[8320, 2611, 2807, 701], [8320, 2611, 2807, 608], [8320, 9418, 2807, 1240], [9419, 1036, 3810, 2784, 9147], [9419, 1036, 3810, 2784, 7432], [1426, 8320, 609, 2807, 518], [5788, 5356, 2831, 2784]]


In [23]:
##We need to use this on embedding vectors , these are absically indexes, like if i exapnd it in vector then ye us index pe 1 hoga wo particular word


In [24]:
#we will try to convetr all ur word based on our index
#like first me the glass of milk and the g;ass of juice likha hai to dekho us word_embedding me
#saara same hai abs ek last me different hai  ,
#If i apply PCA(principle component analysus), like 300dimensio to 2 dimension

#here if we plot it on 2d plane then from embedding layer i can find out thatw hcih vector is near to which one
# and here the most important things means cosine similarity is applied
#Eg-Recommendation SYstem bhi ye use krta hai


#since we have problem with One Hot ending so we will use its index and then do word embedding


In [25]:
#Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [26]:
#Pad_seqeunce is very important
#since we will build sequential model so we also import sequential

In [27]:
import numpy as np


In [28]:
#Pad Seqeunce
#___________
#Observe each and every sentence like not every sentence have same number of words so, we need to make all these sentence of equal size else we will not be able to train in our RNN, because at the end of day for training in RNN it will go with th fixed number for words for a certain fixed number of timestamps


In [29]:
sent_length=8 #becase i know all the words have an average size of 5
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8320 2611 2807  701]
 [   0    0    0    0 8320 2611 2807  608]
 [   0    0    0    0 8320 9418 2807 1240]
 [   0    0    0 9419 1036 3810 2784 9147]
 [   0    0    0 9419 1036 3810 2784 7432]
 [   0    0    0 1426 8320  609 2807  518]
 [   0    0    0    0 5788 5356 2831 2784]]


In [30]:
#Feature Representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step


array([[[ 0.00295997, -0.03734392,  0.02538452,  0.04989847,
         -0.04989356,  0.0299652 , -0.01764797, -0.03166511,
         -0.03194667,  0.04185433],
        [ 0.00295997, -0.03734392,  0.02538452,  0.04989847,
         -0.04989356,  0.0299652 , -0.01764797, -0.03166511,
         -0.03194667,  0.04185433],
        [ 0.00295997, -0.03734392,  0.02538452,  0.04989847,
         -0.04989356,  0.0299652 , -0.01764797, -0.03166511,
         -0.03194667,  0.04185433],
        [ 0.00295997, -0.03734392,  0.02538452,  0.04989847,
         -0.04989356,  0.0299652 , -0.01764797, -0.03166511,
         -0.03194667,  0.04185433],
        [ 0.04826437,  0.02305598,  0.00296279,  0.01974824,
         -0.022671  , -0.02173137,  0.00358323,  0.01151155,
         -0.02301459,  0.04153508],
        [-0.02109405, -0.02283133,  0.01043851, -0.02051575,
          0.03057842, -0.0343382 ,  0.04857396, -0.02098894,
          0.03183848, -0.01642673],
        [-0.01970137,  0.03428913, -0.01640434,  0.0